#!/usr/bin/env node
/* eslint-disable global-require, import/no-dynamic-require */
const crypto = require('crypto')
const stringify = require('querystring')
const program = require('commander')

function generateButton(deployId, repository, ref) {
  const { PRIVATE_KEY } = process.env

  if (!PRIVATE_KEY) {
    console.log(
      'Environment variable PRIVATE_KEY is required to sign de release',
    )
    process.exit(1)
  }

  const [owner, repo] = repository.split('/')
  const [, , refName] = ref.split('/')

  const sign = crypto.createSign('RSA-SHA256')

  const query = stringify({
    owner,
    repo,
    deploy: deployId,
    tag: refName,
    sign: sign.sign(PRIVATE_KEY, 'hex'),
  })

  const url = `https://auto-deploy.inextenso.io/deploy?${query}`
  const img =
    'https://img.shields.io/badge/Deploy%20to-Production-orange.svg?style=for-the-badge'

  return `[![Deploy to prod](${img})](${url})`
}

program.command('generate-button <deployer-id>')
program.action((cmd, deployerId) => {
  try {
    const { GITHUB_REPOSITORY, GITHUB_REF } = process.env
    generateButton(deployerId, GITHUB_REPOSITORY, GITHUB_REF)
  } catch (error) {
    program.outputHelp()
  }
})

module.exports = function() {
  program.parse(process.argv)
}
