#!/usr/bin/env node
/* eslint-disable global-require, import/no-dynamic-require */
const crypto = require('crypto')
const { stringify } = require('querystring')
const program = require('commander')

function generateButton(deployId) {
  const { PRIVATE_KEY, GITHUB_REPOSITORY, GITHUB_REF } = process.env

  if (!PRIVATE_KEY) {
    console.log(
      'Environment variable PRIVATE_KEY is required to sign de release',
    )
    process.exit(1)
  }

  const [owner, repo] = GITHUB_REPOSITORY.split('/')
  const [, , refName] = GITHUB_REF.split('/')

  const sign = crypto.createSign('RSA-SHA256')

  const query = stringify({
    owner,
    repo,
    deploy: deployId,
    tag: refName,
    sign: sign.sign(PRIVATE_KEY, 'hex'),
  })

  const url = `https://auto-deploy.inextenso.io/deploy?${query}`
  const img =
    'https://img.shields.io/badge/Deploy%20to-Production-orange.svg?style=for-the-badge'

  console.log(`[![Deploy to prod](${img})](${url})`)
}

program.command('generate-button <deployer-id>').action(generateButton)

try {
  program.parse(process.argv)
} catch (err) {
  console.error(`${err}\n`)
  program.outputHelp(help => {
    console.error(help)
  })
  process.exit(1)
}
