## REUSABLE WORKFLOW
name: automatic PR

on:
  workflow_call:
    inputs:
      base_branch:
        type: string
        required: true
      head_branch: 
        type: string
        required: true
    secrets:
      botToken:
        required: true

jobs:
  automatic-master-dev-pr:
    name: create ${{ inputs.head_branch }} → ${{ inputs.base_branch }} PR
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@master

      - name: create pr
        id: create-pr
        env:
          GITHUB_TOKEN: ${{ secrets.botToken }}
        run: |
          gh pr create --base ${{ inputs.base_branch }} --head ${{ inputs.head_branch }} --title "{{ inputs.head_branch }} → ${{ inputs.base_branch }}" --body "" --label automerge --repo $GITHUB_REPOSITORY > pull_request.md
          PR_NUMBER=$( basename $(cat pull_request.md) )
          echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT

      - name: enable auto-merge
        id: enable-auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.botToken }}
        run: gh pr merge ${{ steps.create-pr.outputs.pr_number }} --auto --merge --repo $GITHUB_REPOSITORY

      - name: review pr
        id: review-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr review ${{ steps.create-pr.outputs.pr_number }} --approve --repo $GITHUB_REPOSITORY
