## REUSABLE WORKFLOW
name: automatic create master → dev PR

on:
  push:
    branches:
      - master

jobs:
  auto-create-master-dev-pr:
    name: create master → dev PR
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@master

      - name: create pr
        env:
          GITHUB_TOKEN: ${{ secrets.IEDBOT_TOKEN }}
        run: gh pr create --base dev --head master --title "master → dev" --body "" --label automerge --repo $GITHUB_REPOSITORY || exit 0
