## REUSABLE WORKFLOW
name: Update deployment failure Workflow

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
jobs:
  update-deployment-on-failure:
    name: Update deployment
    runs-on: ubuntu-latest
    steps:
      - name: retrieve DEPLOY_ID
        uses: actions/download-artifact@master
        with:
          name: DEPLOY_ID
          path: .

      - name: "update deployment status [FAILURE]"
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST \
            repos/${GITHUB_REPOSITORY}/deployments/$(cat DEPLOY_ID)/statuses \
            -H "Accept: application/vnd.github+json" \
            -F environment=${{ inputs.stage }} \
            -F state='failure' \
            -F description='Deployment failed.'

      - name: update release note
        if: ${{ failure() && inputs.stage == 'prod' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          substitute() {
            perl -i -0pe "s/$1/$2/s" $3
          }
          LATEST_RELEASE=$(gh release list -L 1 -R $GITHUB_REPOSITORY | cut -f 3)
          gh release view $LATEST_RELEASE --json body --jq '.body' > release.md
          # Remove deploy button
          now=$(date '+%Y-%m-%d %H:%M:%S')
          substitute '### :truck: Deployment in Progress...' "## :x: Deployement failed on \\\`$now\\\`" release.md
          gh release edit $TAG_NAME --notes-file release.md
